server:
  port: 8090

spring:
  application:
    name: gateway
#  config:
#    import: optional:configserver:http://localhost:8081
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # microservicio viaje
            - id: msvc-viaje
              uri: http://localhost:8001
              predicates:
                - Path=api/viaje/**

            # microservicio factura
            - id: msvc-factura
              uri: http://localhost:8002
              predicates:
                - Path=api/factura/**

            # microservicio usuario
            - id: msvc-usuario
              uri: http://localhost:8003
              predicates:
                - Path=api/usuario/**

            # microservicio monopatin
            - id: msvc-monopatin
              uri: http://localhost:8004
              predicates:
                - Path=api/monopatin/**

            # microservicio parada
            - id: msvc-parada
              uri: http://localhost:8005
              predicates:
                - Path=api/parada/**

            # microservicio cuenta
            - id: msvc-cuenta
              uri: http://localhost:8007
              predicates:
                - Path=api/cuenta/**

            # microservicio tarifa
            - id: msvc-tarifa
              uri: http://localhost:8008
              predicates:
                - Path=api/tarifa/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG