server:
  port: 8009

spring:
  application:
    name: msvc-ia

groq:
  api-key: ${GROQ_API_KEY}
  base-url: https://api.groq.com/openai
  model: llama-3.1-8b-instant   # o llama3-70b-8192 si querés más calidad
  temperature: 0.3


